declare module '@editorjs/link';
declare module '@calumk/editorjs-codecup';
declare module 'editorjs-latex';
declare module 'editorjs-table';
declare module 'editorjs-md-parser';
declare module '@editorjs/marker';
declare module 'editorjs-text-color-plugin';
declare module 'color-plugin-editorjs';
declare module 'editorjs-button';
