import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastProvider } from "@/components/providers/toast-provider";
import ConfettiProvider from "@/components/providers/confetti-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { SessionProvider } from "next-auth/react";
import { isTeacher } from "@/lib/teacher";
import { auth } from "@/auth";
import FacebookMessenger from "@/components/facebook-messenger";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    // <ClerkProvider>
    <html lang="zh" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ConfettiProvider />

          <ToastProvider />
          <SessionProvider session={session}>{children}</SessionProvider>
        </ThemeProvider>
      </body>

      {!isTeacher(session) && <FacebookMessenger />}
    </html>
    // </ClerkProvider>
  );
}
